<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <base href="/localhost" />
        <meta charset="UTF-8" />
        <title>{ssadfdsfsa}</title>
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <link rel="stylesheet" href="view/style.css" type="text/css"/>
    </head>

    <body>
        <div class="content">
            <header>
                <?php $this->controller->renderHeader(); // vložení aktuálního pohledu do šablony ?>
            </header>

            <nav>
                <?php $this->controller->renderNavigation(); // vložení aktuálního pohledu do šablony ?>
            </nav>
            <br clear="both" />

            <article>
                <?php $this->controller->renderAlert(); // vložení aktuálního pohledu do šablony ?>
                <?php $this->controller->renderContent(); // vložení aktuálního pohledu do šablony ?>
                <?php //$this->controller->renderPaginace(); ?>
            </article>

            <footer>

            </footer>
        </div>
    </body>
</html>