<div class="menu">
    <ul>
        <li>
            <a href="postavy">Postavy</a>
            <ul>
                <li>
                    <a href="postavy">Seznam postav</a>
                </li>

                <li>
                    <a href="postavy/obnoveni">Obnovení postavy</a>
                </li>
            </ul>
        </li>

        <li>
            <a href="heslo">Změna hesla</a>
        </li>
    </ul>
</div>

